version: '3'

services:
  php:
    env_file: ./.env
    build:
      context: ./etc/php
    container_name: ${APP_NAME}_php
    entrypoint: sh /bin/entrypoint.sh php-fpm
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./etc/php/entrypoint.sh:/bin/entrypoint.sh"
      - ${APP_PATH}:/var/www
    links:
      - db:db
    expose:
      - 9000
    depends_on:
      - db
    networks:
      - internal
  db:
    env_file: ./.env
    build:
      context: ./etc/mysql
    container_name: ${APP_NAME}_db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - "./data/mysql/dev:/var/lib/mysql"
    ports:
      - 3301:3306
    networks:
      - internal
  web:
    env_file: ./.env
    build: ./etc/nginx
    container_name: ${APP_NAME}_nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./etc/nginx/app.conf:/etc/nginx/sites-available/application.conf"
      - "./etc/nginx/app.conf:/etc/nginx/sites-enabled/application"
      - "./var/log/nginx:/var/log/nginx"
      - ${APP_PATH}:/var/www
    depends_on:
      - php
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.121.0/28